services:
  app:
    build: ./Build/App
    working_dir: /application
    volumes:
      - '.:/application'
      - "./Build/App/openssl.cnf.override:/etc/ssl/openssl.cnf"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=test.sheet.com.br"
    networks:
      - framework

  nginx:
    image: "nginx:1.27"
    restart: always
    links:
      - app
    working_dir: /application
    volumes:
      - '.:/application'
      - "./Build/App/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    networks:
      - framework

  postgres:
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - database:/var/lib/postgresql/data
      - ./Migration/Initialization/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    networks:
      - framework

  redis:
    image: "redis:7.0"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - framework

  ngrok:
    image: wernight/ngrok
    command: ngrok http nginx:80
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    depends_on:
      - nginx
    networks:
      - framework

volumes:
  database:

networks:
  framework:
    driver: bridge
